version: 2

models:
  - name: bike_point_availability
    description: "Analytics-ready bike point data with availability metrics, categoriation, and type conversions"
    columns:
      - name: id
        description: "Unique identifier for the bike point"
        tests:
          - unique
          - not_null

      - name: common_name
        description: "Common name of the bike point location"

      - name: terminal_name
        description: "Terminal identifier for the bike point"

      - name: bikes_available
        description: "Total number of bikes currently available"

      - name: standard_bikes_available
        description: "Number of standard (non-electric) bikes available"

      - name: ebikes_available
        description: "Number of electric bikes available"

      - name: empty_docks
        description: "Number of empty docking stations"

      - name: total_docks
        description: "Total number of docking stations"

      - name: utilization_pct
        description: "Percentage of docks currently occupied by bikes (0-100)"

      - name: availability_pct
        description: "Percentage of docks currently empty (0-100)"

      - name: availability_status
        description: "Categorized availability status based on bike-to-dock ratio"
        tests:
          - accepted_values:
              arguments:
                values: ['Empty', 'Low', 'Medium', 'High', 'Full']

      - name: is_installed
        description: "Whether the bike point is currently installed"

      - name: is_locked
        description: "Whether the bike point is locked"

      - name: is_temporary
        description: "Whether the bike point is temporary"

      - name: install_timestamp
        description: "Timestamp when the bike point was installed"
